2018-08-30 15:00:14,912  WARN [org.apache.hadoop.mapreduce.JobResourceUploader] - Hadoop command-line option parsing not performed. Implement the Tool interface and execute your application with ToolRunner to remedy this.
2018-08-30 15:00:14,996  WARN [org.apache.hadoop.mapreduce.JobResourceUploader] - No job jar file set.  User classes may not be found. See Job or Job#setJar(String).
2018-08-30 15:02:18,424  WARN [org.apache.hadoop.mapreduce.JobResourceUploader] - Hadoop command-line option parsing not performed. Implement the Tool interface and execute your application with ToolRunner to remedy this.
2018-08-30 15:02:18,521  WARN [org.apache.hadoop.mapreduce.JobResourceUploader] - No job jar file set.  User classes may not be found. See Job or Job#setJar(String).
2018-08-30 15:07:56,942  WARN [org.apache.hadoop.mapreduce.JobResourceUploader] - Hadoop command-line option parsing not performed. Implement the Tool interface and execute your application with ToolRunner to remedy this.
2018-08-30 15:07:57,025  WARN [org.apache.hadoop.mapreduce.JobResourceUploader] - No job jar file set.  User classes may not be found. See Job or Job#setJar(String).
2018-08-30 15:38:33,677  WARN [org.apache.hadoop.mapreduce.JobResourceUploader] - Hadoop command-line option parsing not performed. Implement the Tool interface and execute your application with ToolRunner to remedy this.
2018-08-30 15:38:33,760  WARN [org.apache.hadoop.mapreduce.JobResourceUploader] - No job jar file set.  User classes may not be found. See Job or Job#setJar(String).
2018-08-30 15:38:36,953  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1281914888_0001_r_000000_0\.09-r-00000.crc]: it still exists.
2018-08-30 15:38:36,954  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1281914888_0001_r_000000_0\.AB-r-00000.crc]: it still exists.
2018-08-30 15:38:36,954  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1281914888_0001_r_000000_0\.az-r-00000.crc]: it still exists.
2018-08-30 15:38:36,954  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1281914888_0001_r_000000_0\.others-r-00000.crc]: it still exists.
2018-08-30 15:38:36,955  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1281914888_0001_r_000000_0\09-r-00000]: it still exists.
2018-08-30 15:38:36,955  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1281914888_0001_r_000000_0\AB-r-00000]: it still exists.
2018-08-30 15:38:36,956  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1281914888_0001_r_000000_0\az-r-00000]: it still exists.
2018-08-30 15:38:36,956  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1281914888_0001_r_000000_0\others-r-00000]: it still exists.
2018-08-30 15:38:36,957  WARN [org.apache.hadoop.mapred.Task] - Failure committing: java.io.IOException: Could not rename file:/F:/Data/GP1809/wordcount/multiFilesout/_temporary/0/_temporary/attempt_local1281914888_0001_r_000000_0 to file:/F:/Data/GP1809/wordcount/multiFilesout/_temporary/0/task_local1281914888_0001_r_000000
	at org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter.commitTask(FileOutputCommitter.java:479)
	at org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter.commitTask(FileOutputCommitter.java:449)
	at org.apache.hadoop.mapred.Task.commit(Task.java:1200)
	at org.apache.hadoop.mapred.Task.done(Task.java:1062)
	at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:397)
	at org.apache.hadoop.mapred.LocalJobRunner$Job$ReduceTaskRunnable.run(LocalJobRunner.java:319)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

2018-08-30 15:38:36,960  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1281914888_0001_r_000000_0\.09-r-00000.crc]: it still exists.
2018-08-30 15:38:36,960  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1281914888_0001_r_000000_0\.AB-r-00000.crc]: it still exists.
2018-08-30 15:38:36,961  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1281914888_0001_r_000000_0\.az-r-00000.crc]: it still exists.
2018-08-30 15:38:36,961  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1281914888_0001_r_000000_0\.others-r-00000.crc]: it still exists.
2018-08-30 15:38:36,962  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1281914888_0001_r_000000_0\09-r-00000]: it still exists.
2018-08-30 15:38:36,962  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1281914888_0001_r_000000_0\AB-r-00000]: it still exists.
2018-08-30 15:38:36,963  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1281914888_0001_r_000000_0\az-r-00000]: it still exists.
2018-08-30 15:38:36,963  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1281914888_0001_r_000000_0\others-r-00000]: it still exists.
2018-08-30 15:38:36,964  WARN [org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter] - Could not delete file:/F:/Data/GP1809/wordcount/multiFilesout/_temporary/0/_temporary/attempt_local1281914888_0001_r_000000_0
2018-08-30 15:38:36,988  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1281914888_0001_r_000000_0\.09-r-00000.crc]: it still exists.
2018-08-30 15:38:36,989  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1281914888_0001_r_000000_0\.AB-r-00000.crc]: it still exists.
2018-08-30 15:38:36,989  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1281914888_0001_r_000000_0\.az-r-00000.crc]: it still exists.
2018-08-30 15:38:36,990  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1281914888_0001_r_000000_0\.others-r-00000.crc]: it still exists.
2018-08-30 15:38:36,990  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1281914888_0001_r_000000_0\09-r-00000]: it still exists.
2018-08-30 15:38:36,991  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1281914888_0001_r_000000_0\AB-r-00000]: it still exists.
2018-08-30 15:38:36,991  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1281914888_0001_r_000000_0\az-r-00000]: it still exists.
2018-08-30 15:38:36,991  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1281914888_0001_r_000000_0\others-r-00000]: it still exists.
2018-08-30 15:38:36,992  WARN [org.apache.hadoop.mapred.LocalJobRunner] - job_local1281914888_0001
java.lang.Exception: java.io.IOException: Could not rename file:/F:/Data/GP1809/wordcount/multiFilesout/_temporary/0/_temporary/attempt_local1281914888_0001_r_000000_0 to file:/F:/Data/GP1809/wordcount/multiFilesout/_temporary/0/task_local1281914888_0001_r_000000
	at org.apache.hadoop.mapred.LocalJobRunner$Job.runTasks(LocalJobRunner.java:462)
	at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:529)
Caused by: java.io.IOException: Could not rename file:/F:/Data/GP1809/wordcount/multiFilesout/_temporary/0/_temporary/attempt_local1281914888_0001_r_000000_0 to file:/F:/Data/GP1809/wordcount/multiFilesout/_temporary/0/task_local1281914888_0001_r_000000
	at org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter.commitTask(FileOutputCommitter.java:479)
	at org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter.commitTask(FileOutputCommitter.java:449)
	at org.apache.hadoop.mapred.Task.commit(Task.java:1200)
	at org.apache.hadoop.mapred.Task.done(Task.java:1062)
	at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:397)
	at org.apache.hadoop.mapred.LocalJobRunner$Job$ReduceTaskRunnable.run(LocalJobRunner.java:319)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2018-08-30 15:42:14,923  WARN [org.apache.hadoop.mapreduce.JobResourceUploader] - Hadoop command-line option parsing not performed. Implement the Tool interface and execute your application with ToolRunner to remedy this.
2018-08-30 15:42:14,970  WARN [org.apache.hadoop.mapreduce.JobResourceUploader] - No job jar file set.  User classes may not be found. See Job or Job#setJar(String).
2018-08-30 15:42:17,445  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1027368001_0001_r_000000_0\.09-r-00000.crc]: it still exists.
2018-08-30 15:42:17,445  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1027368001_0001_r_000000_0\.AB-r-00000.crc]: it still exists.
2018-08-30 15:42:17,445  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1027368001_0001_r_000000_0\.az-r-00000.crc]: it still exists.
2018-08-30 15:42:17,445  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1027368001_0001_r_000000_0\.others-r-00000.crc]: it still exists.
2018-08-30 15:42:17,445  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1027368001_0001_r_000000_0\09-r-00000]: it still exists.
2018-08-30 15:42:17,445  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1027368001_0001_r_000000_0\AB-r-00000]: it still exists.
2018-08-30 15:42:17,445  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1027368001_0001_r_000000_0\az-r-00000]: it still exists.
2018-08-30 15:42:17,445  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1027368001_0001_r_000000_0\others-r-00000]: it still exists.
2018-08-30 15:42:17,445  WARN [org.apache.hadoop.mapred.Task] - Failure committing: java.io.IOException: Could not rename file:/F:/Data/GP1809/wordcount/multiFilesout/_temporary/0/_temporary/attempt_local1027368001_0001_r_000000_0 to file:/F:/Data/GP1809/wordcount/multiFilesout/_temporary/0/task_local1027368001_0001_r_000000
	at org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter.commitTask(FileOutputCommitter.java:479)
	at org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter.commitTask(FileOutputCommitter.java:449)
	at org.apache.hadoop.mapred.Task.commit(Task.java:1200)
	at org.apache.hadoop.mapred.Task.done(Task.java:1062)
	at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:397)
	at org.apache.hadoop.mapred.LocalJobRunner$Job$ReduceTaskRunnable.run(LocalJobRunner.java:319)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

2018-08-30 15:42:17,449  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1027368001_0001_r_000000_0\.09-r-00000.crc]: it still exists.
2018-08-30 15:42:17,449  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1027368001_0001_r_000000_0\.AB-r-00000.crc]: it still exists.
2018-08-30 15:42:17,449  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1027368001_0001_r_000000_0\.az-r-00000.crc]: it still exists.
2018-08-30 15:42:17,449  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1027368001_0001_r_000000_0\.others-r-00000.crc]: it still exists.
2018-08-30 15:42:17,453  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1027368001_0001_r_000000_0\09-r-00000]: it still exists.
2018-08-30 15:42:17,453  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1027368001_0001_r_000000_0\AB-r-00000]: it still exists.
2018-08-30 15:42:17,453  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1027368001_0001_r_000000_0\az-r-00000]: it still exists.
2018-08-30 15:42:17,453  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1027368001_0001_r_000000_0\others-r-00000]: it still exists.
2018-08-30 15:42:17,453  WARN [org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter] - Could not delete file:/F:/Data/GP1809/wordcount/multiFilesout/_temporary/0/_temporary/attempt_local1027368001_0001_r_000000_0
2018-08-30 15:42:17,468  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1027368001_0001_r_000000_0\.09-r-00000.crc]: it still exists.
2018-08-30 15:42:17,468  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1027368001_0001_r_000000_0\.AB-r-00000.crc]: it still exists.
2018-08-30 15:42:17,468  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1027368001_0001_r_000000_0\.az-r-00000.crc]: it still exists.
2018-08-30 15:42:17,468  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1027368001_0001_r_000000_0\.others-r-00000.crc]: it still exists.
2018-08-30 15:42:17,468  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1027368001_0001_r_000000_0\09-r-00000]: it still exists.
2018-08-30 15:42:17,468  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1027368001_0001_r_000000_0\AB-r-00000]: it still exists.
2018-08-30 15:42:17,468  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1027368001_0001_r_000000_0\az-r-00000]: it still exists.
2018-08-30 15:42:17,468  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1027368001_0001_r_000000_0\others-r-00000]: it still exists.
2018-08-30 15:42:17,468  WARN [org.apache.hadoop.mapred.LocalJobRunner] - job_local1027368001_0001
java.lang.Exception: java.io.IOException: Could not rename file:/F:/Data/GP1809/wordcount/multiFilesout/_temporary/0/_temporary/attempt_local1027368001_0001_r_000000_0 to file:/F:/Data/GP1809/wordcount/multiFilesout/_temporary/0/task_local1027368001_0001_r_000000
	at org.apache.hadoop.mapred.LocalJobRunner$Job.runTasks(LocalJobRunner.java:462)
	at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:529)
Caused by: java.io.IOException: Could not rename file:/F:/Data/GP1809/wordcount/multiFilesout/_temporary/0/_temporary/attempt_local1027368001_0001_r_000000_0 to file:/F:/Data/GP1809/wordcount/multiFilesout/_temporary/0/task_local1027368001_0001_r_000000
	at org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter.commitTask(FileOutputCommitter.java:479)
	at org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter.commitTask(FileOutputCommitter.java:449)
	at org.apache.hadoop.mapred.Task.commit(Task.java:1200)
	at org.apache.hadoop.mapred.Task.done(Task.java:1062)
	at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:397)
	at org.apache.hadoop.mapred.LocalJobRunner$Job$ReduceTaskRunnable.run(LocalJobRunner.java:319)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2018-08-30 16:11:05,829  WARN [org.apache.hadoop.mapreduce.JobResourceUploader] - Hadoop command-line option parsing not performed. Implement the Tool interface and execute your application with ToolRunner to remedy this.
2018-08-30 16:11:06,065  WARN [org.apache.hadoop.mapreduce.JobResourceUploader] - No job jar file set.  User classes may not be found. See Job or Job#setJar(String).
2018-08-30 16:13:18,674  WARN [org.apache.hadoop.mapreduce.JobResourceUploader] - Hadoop command-line option parsing not performed. Implement the Tool interface and execute your application with ToolRunner to remedy this.
2018-08-30 16:13:18,767  WARN [org.apache.hadoop.mapreduce.JobResourceUploader] - No job jar file set.  User classes may not be found. See Job or Job#setJar(String).
2018-08-30 16:13:21,949  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1756380989_0001_r_000000_0\.09-r-00000.crc]: it still exists.
2018-08-30 16:13:21,950  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1756380989_0001_r_000000_0\.AB-r-00000.crc]: it still exists.
2018-08-30 16:13:21,950  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1756380989_0001_r_000000_0\.az-r-00000.crc]: it still exists.
2018-08-30 16:13:21,951  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1756380989_0001_r_000000_0\.others-r-00000.crc]: it still exists.
2018-08-30 16:13:21,952  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1756380989_0001_r_000000_0\09-r-00000]: it still exists.
2018-08-30 16:13:21,952  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1756380989_0001_r_000000_0\AB-r-00000]: it still exists.
2018-08-30 16:13:21,953  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1756380989_0001_r_000000_0\az-r-00000]: it still exists.
2018-08-30 16:13:21,953  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1756380989_0001_r_000000_0\others-r-00000]: it still exists.
2018-08-30 16:13:21,954  WARN [org.apache.hadoop.mapred.Task] - Failure committing: java.io.IOException: Could not rename file:/F:/Data/GP1809/wordcount/multiFilesout/_temporary/0/_temporary/attempt_local1756380989_0001_r_000000_0 to file:/F:/Data/GP1809/wordcount/multiFilesout/_temporary/0/task_local1756380989_0001_r_000000
	at org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter.commitTask(FileOutputCommitter.java:479)
	at org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter.commitTask(FileOutputCommitter.java:449)
	at org.apache.hadoop.mapred.Task.commit(Task.java:1200)
	at org.apache.hadoop.mapred.Task.done(Task.java:1062)
	at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:397)
	at org.apache.hadoop.mapred.LocalJobRunner$Job$ReduceTaskRunnable.run(LocalJobRunner.java:319)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

2018-08-30 16:13:21,957  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1756380989_0001_r_000000_0\.09-r-00000.crc]: it still exists.
2018-08-30 16:13:21,959  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1756380989_0001_r_000000_0\.AB-r-00000.crc]: it still exists.
2018-08-30 16:13:21,959  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1756380989_0001_r_000000_0\.az-r-00000.crc]: it still exists.
2018-08-30 16:13:21,960  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1756380989_0001_r_000000_0\.others-r-00000.crc]: it still exists.
2018-08-30 16:13:21,960  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1756380989_0001_r_000000_0\09-r-00000]: it still exists.
2018-08-30 16:13:21,961  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1756380989_0001_r_000000_0\AB-r-00000]: it still exists.
2018-08-30 16:13:21,961  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1756380989_0001_r_000000_0\az-r-00000]: it still exists.
2018-08-30 16:13:21,962  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1756380989_0001_r_000000_0\others-r-00000]: it still exists.
2018-08-30 16:13:21,985  WARN [org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter] - Could not delete file:/F:/Data/GP1809/wordcount/multiFilesout/_temporary/0/_temporary/attempt_local1756380989_0001_r_000000_0
2018-08-30 16:13:22,005  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1756380989_0001_r_000000_0\.09-r-00000.crc]: it still exists.
2018-08-30 16:13:22,005  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1756380989_0001_r_000000_0\.AB-r-00000.crc]: it still exists.
2018-08-30 16:13:22,006  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1756380989_0001_r_000000_0\.az-r-00000.crc]: it still exists.
2018-08-30 16:13:22,007  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1756380989_0001_r_000000_0\.others-r-00000.crc]: it still exists.
2018-08-30 16:13:22,008  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1756380989_0001_r_000000_0\09-r-00000]: it still exists.
2018-08-30 16:13:22,009  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1756380989_0001_r_000000_0\AB-r-00000]: it still exists.
2018-08-30 16:13:22,009  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1756380989_0001_r_000000_0\az-r-00000]: it still exists.
2018-08-30 16:13:22,009  WARN [org.apache.hadoop.fs.FileUtil] - Failed to delete file or dir [F:\Data\GP1809\wordcount\multiFilesout\_temporary\0\_temporary\attempt_local1756380989_0001_r_000000_0\others-r-00000]: it still exists.
2018-08-30 16:13:22,011  WARN [org.apache.hadoop.mapred.LocalJobRunner] - job_local1756380989_0001
java.lang.Exception: java.io.IOException: Could not rename file:/F:/Data/GP1809/wordcount/multiFilesout/_temporary/0/_temporary/attempt_local1756380989_0001_r_000000_0 to file:/F:/Data/GP1809/wordcount/multiFilesout/_temporary/0/task_local1756380989_0001_r_000000
	at org.apache.hadoop.mapred.LocalJobRunner$Job.runTasks(LocalJobRunner.java:462)
	at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:529)
Caused by: java.io.IOException: Could not rename file:/F:/Data/GP1809/wordcount/multiFilesout/_temporary/0/_temporary/attempt_local1756380989_0001_r_000000_0 to file:/F:/Data/GP1809/wordcount/multiFilesout/_temporary/0/task_local1756380989_0001_r_000000
	at org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter.commitTask(FileOutputCommitter.java:479)
	at org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter.commitTask(FileOutputCommitter.java:449)
	at org.apache.hadoop.mapred.Task.commit(Task.java:1200)
	at org.apache.hadoop.mapred.Task.done(Task.java:1062)
	at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:397)
	at org.apache.hadoop.mapred.LocalJobRunner$Job$ReduceTaskRunnable.run(LocalJobRunner.java:319)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2018-08-30 16:36:51,411  WARN [org.apache.hadoop.mapreduce.JobResourceUploader] - Hadoop command-line option parsing not performed. Implement the Tool interface and execute your application with ToolRunner to remedy this.
2018-08-30 16:36:51,542  WARN [org.apache.hadoop.mapreduce.JobResourceUploader] - No job jar file set.  User classes may not be found. See Job or Job#setJar(String).
2018-08-30 16:36:53,892  WARN [org.apache.hadoop.mapred.LocalJobRunner] - job_local1800701187_0001
java.lang.Exception: java.io.IOException: Type mismatch in value from map: expected org.apache.hadoop.io.Text, received org.apache.hadoop.io.IntWritable
	at org.apache.hadoop.mapred.LocalJobRunner$Job.runTasks(LocalJobRunner.java:462)
	at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:522)
Caused by: java.io.IOException: Type mismatch in value from map: expected org.apache.hadoop.io.Text, received org.apache.hadoop.io.IntWritable
	at org.apache.hadoop.mapred.MapTask$MapOutputBuffer.collect(MapTask.java:1079)
	at org.apache.hadoop.mapred.MapTask$NewOutputCollector.write(MapTask.java:715)
	at org.apache.hadoop.mapreduce.task.TaskInputOutputContextImpl.write(TaskInputOutputContextImpl.java:89)
	at org.apache.hadoop.mapreduce.lib.map.WrappedMapper$Context.write(WrappedMapper.java:112)
	at com.qfedu.bigdata.mr.day14.partitionerDemo$MyMapper.map(partitionerDemo.java:63)
	at com.qfedu.bigdata.mr.day14.partitionerDemo$MyMapper.map(partitionerDemo.java:30)
	at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:146)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
	at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:243)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2018-08-30 16:37:43,267  WARN [org.apache.hadoop.mapreduce.JobResourceUploader] - Hadoop command-line option parsing not performed. Implement the Tool interface and execute your application with ToolRunner to remedy this.
2018-08-30 16:37:43,355  WARN [org.apache.hadoop.mapreduce.JobResourceUploader] - No job jar file set.  User classes may not be found. See Job or Job#setJar(String).
2018-08-30 16:39:27,277  WARN [org.apache.hadoop.mapreduce.JobResourceUploader] - Hadoop command-line option parsing not performed. Implement the Tool interface and execute your application with ToolRunner to remedy this.
2018-08-30 16:39:27,358  WARN [org.apache.hadoop.mapreduce.JobResourceUploader] - No job jar file set.  User classes may not be found. See Job or Job#setJar(String).
2018-08-30 16:39:29,235  WARN [org.apache.hadoop.mapred.LocalJobRunner] - job_local730016501_0001
java.lang.Exception: java.lang.ClassCastException: org.apache.hadoop.io.Text cannot be cast to javax.xml.soap.Text
	at org.apache.hadoop.mapred.LocalJobRunner$Job.runTasks(LocalJobRunner.java:462)
	at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:522)
Caused by: java.lang.ClassCastException: org.apache.hadoop.io.Text cannot be cast to javax.xml.soap.Text
	at com.qfedu.bigdata.mr.day14.MyPartitionerDemo.getPartition(MyPartitionerDemo.java:24)
	at org.apache.hadoop.mapred.MapTask$NewOutputCollector.write(MapTask.java:716)
	at org.apache.hadoop.mapreduce.task.TaskInputOutputContextImpl.write(TaskInputOutputContextImpl.java:89)
	at org.apache.hadoop.mapreduce.lib.map.WrappedMapper$Context.write(WrappedMapper.java:112)
	at com.qfedu.bigdata.mr.day14.partitionerDemo$MyMapper.map(partitionerDemo.java:63)
	at com.qfedu.bigdata.mr.day14.partitionerDemo$MyMapper.map(partitionerDemo.java:30)
	at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:146)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
	at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:243)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2018-08-30 16:41:31,615  WARN [org.apache.hadoop.mapreduce.JobResourceUploader] - Hadoop command-line option parsing not performed. Implement the Tool interface and execute your application with ToolRunner to remedy this.
2018-08-30 16:41:31,684  WARN [org.apache.hadoop.mapreduce.JobResourceUploader] - No job jar file set.  User classes may not be found. See Job or Job#setJar(String).
2018-08-30 16:41:33,555  WARN [org.apache.hadoop.mapred.LocalJobRunner] - job_local1578225736_0001
java.lang.Exception: java.lang.ClassCastException: org.apache.hadoop.io.Text cannot be cast to javax.xml.soap.Text
	at org.apache.hadoop.mapred.LocalJobRunner$Job.runTasks(LocalJobRunner.java:462)
	at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:522)
Caused by: java.lang.ClassCastException: org.apache.hadoop.io.Text cannot be cast to javax.xml.soap.Text
	at com.qfedu.bigdata.mr.day14.MyPartitionerDemo.getPartition(MyPartitionerDemo.java:24)
	at org.apache.hadoop.mapred.MapTask$NewOutputCollector.write(MapTask.java:716)
	at org.apache.hadoop.mapreduce.task.TaskInputOutputContextImpl.write(TaskInputOutputContextImpl.java:89)
	at org.apache.hadoop.mapreduce.lib.map.WrappedMapper$Context.write(WrappedMapper.java:112)
	at com.qfedu.bigdata.mr.day14.partitionerDemo$MyMapper.map(partitionerDemo.java:60)
	at com.qfedu.bigdata.mr.day14.partitionerDemo$MyMapper.map(partitionerDemo.java:27)
	at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:146)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
	at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:243)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2018-08-30 16:42:54,607  WARN [org.apache.hadoop.mapreduce.JobResourceUploader] - Hadoop command-line option parsing not performed. Implement the Tool interface and execute your application with ToolRunner to remedy this.
2018-08-30 16:42:54,689  WARN [org.apache.hadoop.mapreduce.JobResourceUploader] - No job jar file set.  User classes may not be found. See Job or Job#setJar(String).
2018-08-30 16:44:06,291  WARN [org.apache.hadoop.mapreduce.JobResourceUploader] - Hadoop command-line option parsing not performed. Implement the Tool interface and execute your application with ToolRunner to remedy this.
2018-08-30 16:44:06,342  WARN [org.apache.hadoop.mapreduce.JobResourceUploader] - No job jar file set.  User classes may not be found. See Job or Job#setJar(String).
2018-08-30 16:44:50,606  WARN [org.apache.hadoop.mapreduce.JobResourceUploader] - Hadoop command-line option parsing not performed. Implement the Tool interface and execute your application with ToolRunner to remedy this.
2018-08-30 16:44:50,684  WARN [org.apache.hadoop.mapreduce.JobResourceUploader] - No job jar file set.  User classes may not be found. See Job or Job#setJar(String).
2018-08-30 16:44:52,618  WARN [org.apache.hadoop.mapred.LocalJobRunner] - job_local1892906697_0001
java.lang.Exception: java.io.IOException: Illegal partition for Hello (2)
	at org.apache.hadoop.mapred.LocalJobRunner$Job.runTasks(LocalJobRunner.java:462)
	at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:522)
Caused by: java.io.IOException: Illegal partition for Hello (2)
	at org.apache.hadoop.mapred.MapTask$MapOutputBuffer.collect(MapTask.java:1082)
	at org.apache.hadoop.mapred.MapTask$NewOutputCollector.write(MapTask.java:715)
	at org.apache.hadoop.mapreduce.task.TaskInputOutputContextImpl.write(TaskInputOutputContextImpl.java:89)
	at org.apache.hadoop.mapreduce.lib.map.WrappedMapper$Context.write(WrappedMapper.java:112)
	at com.qfedu.bigdata.mr.day14.partitionerDemo$MyMapper.map(partitionerDemo.java:60)
	at com.qfedu.bigdata.mr.day14.partitionerDemo$MyMapper.map(partitionerDemo.java:27)
	at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:146)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
	at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:243)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2018-08-30 16:50:59,149  WARN [org.apache.hadoop.mapreduce.JobResourceUploader] - Hadoop command-line option parsing not performed. Implement the Tool interface and execute your application with ToolRunner to remedy this.
2018-08-30 16:50:59,219  WARN [org.apache.hadoop.mapreduce.JobResourceUploader] - No job jar file set.  User classes may not be found. See Job or Job#setJar(String).
